name: nexxplay
description: Plugin for Android native nexxPLAY
version: 1.0.2
homepage: https://play.docs.nexx.cloud/

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: tv.nexx.flutter.android
        pluginClass: NexxPlayPlugin
